//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("World.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many humans do you want to create?.
        /// </summary>
        internal static string HumansAmountQuestion {
            get {
                return ResourceManager.GetString("HumansAmountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid average mark.
        /// </summary>
        internal static string InvalidAverageMark {
            get {
                return ResourceManager.GetString("InvalidAverageMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount of childs.
        /// </summary>
        internal static string InvalidChildsAmount {
            get {
                return ResourceManager.GetString("InvalidChildsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters of human.
        /// </summary>
        internal static string InvalidHumanParams {
            get {
                return ResourceManager.GetString("InvalidHumanParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount of humans given.
        /// </summary>
        internal static string InvalidHumansAmount {
            get {
                return ResourceManager.GetString("InvalidHumansAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid human type.
        /// </summary>
        internal static string InvalidHumanType {
            get {
                return ResourceManager.GetString("InvalidHumanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount of money.
        /// </summary>
        internal static string InvalidMoneyAmount {
            get {
                return ResourceManager.GetString("InvalidMoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parentName.
        /// </summary>
        internal static string InvalidParentName {
            get {
                return ResourceManager.GetString("InvalidParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent name from patronymic.
        /// </summary>
        internal static string InvalidParentNameFromPatronymic {
            get {
                return ResourceManager.GetString("InvalidParentNameFromPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid patronymic.
        /// </summary>
        internal static string InvalidPatronymic {
            get {
                return ResourceManager.GetString("InvalidPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sex.
        /// </summary>
        internal static string InvalidSex {
            get {
                return ResourceManager.GetString("InvalidSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday is a holiday!.
        /// </summary>
        internal static string NoSundayWork {
            get {
                return ResourceManager.GetString("NoSundayWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null human.
        /// </summary>
        internal static string NullHuman {
            get {
                return ResourceManager.GetString("NullHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null parent.
        /// </summary>
        internal static string NullParent {
            get {
                return ResourceManager.GetString("NullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null student.
        /// </summary>
        internal static string NullStudent {
            get {
                return ResourceManager.GetString("NullStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money was written to file {0}.
        /// </summary>
        internal static string SavedMoney {
            get {
                return ResourceManager.GetString("SavedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic is too short.
        /// </summary>
        internal static string ShortPatronymic {
            get {
                return ResourceManager.GetString("ShortPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God console here. Create humans or die!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
