//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedWorld.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedWorld.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child naming not supported.
        /// </summary>
        public static string AdvancedGod_ChildNamingNotSupported {
            get {
                return ResourceManager.GetString("AdvancedGod_ChildNamingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible types.
        /// </summary>
        public static string AdvancedGod_IncompatibleTypes {
            get {
                return ResourceManager.GetString("AdvancedGod_IncompatibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would not work out.
        /// </summary>
        public static string AdvancedGod_WouldNotWorkOut {
            get {
                return ResourceManager.GetString("AdvancedGod_WouldNotWorkOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book .
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid book name.
        /// </summary>
        public static string Book_InvalidName {
            get {
                return ResourceManager.GetString("Book_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botan {0} {1}, {2}, age {3}, {4} average mark.
        /// </summary>
        public static string BotanParamOut {
            get {
                return ResourceManager.GetString("BotanParamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoolParent {0}, {1}, age {2}, {3} childs .
        /// </summary>
        public static string CoolParentParamOut {
            get {
                return ResourceManager.GetString("CoolParentParamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not like each other.
        /// </summary>
        public static string Couple_NoLike {
            get {
                return ResourceManager.GetString("Couple_NoLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid couple classes.
        /// </summary>
        public static string CoupleAttribute_InvalidСoupleСlasses {
            get {
                return ResourceManager.GetString("CoupleAttribute_InvalidСoupleСlasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl {0} {1}, sex: {2}, age: {3}.
        /// </summary>
        public static string GirlParamsOut {
            get {
                return ResourceManager.GetString("GirlParamsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human {0} {1}, age {2}.
        /// </summary>
        public static string HumanParamOut {
            get {
                return ResourceManager.GetString("HumanParamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many humans do you want to create?.
        /// </summary>
        public static string HumansAmountQuestion {
            get {
                return ResourceManager.GetString("HumansAmountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid average mark.
        /// </summary>
        public static string InvalidAverageMark {
            get {
                return ResourceManager.GetString("InvalidAverageMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount of childs.
        /// </summary>
        public static string InvalidChildsAmount {
            get {
                return ResourceManager.GetString("InvalidChildsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters of human.
        /// </summary>
        public static string InvalidHumanParams {
            get {
                return ResourceManager.GetString("InvalidHumanParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount of humans given.
        /// </summary>
        public static string InvalidHumansAmount {
            get {
                return ResourceManager.GetString("InvalidHumansAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid human type.
        /// </summary>
        public static string InvalidHumanType {
            get {
                return ResourceManager.GetString("InvalidHumanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount of money.
        /// </summary>
        public static string InvalidMoneyAmount {
            get {
                return ResourceManager.GetString("InvalidMoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parentName.
        /// </summary>
        public static string InvalidParentName {
            get {
                return ResourceManager.GetString("InvalidParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent name from patronymic.
        /// </summary>
        public static string InvalidParentNameFromPatronymic {
            get {
                return ResourceManager.GetString("InvalidParentNameFromPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid patronymic.
        /// </summary>
        public static string InvalidPatronymic {
            get {
                return ResourceManager.GetString("InvalidPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sex.
        /// </summary>
        public static string InvalidSex {
            get {
                return ResourceManager.GetString("InvalidSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday is a holiday!.
        /// </summary>
        public static string NoSundayWork {
            get {
                return ResourceManager.GetString("NoSundayWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null human.
        /// </summary>
        public static string NullHuman {
            get {
                return ResourceManager.GetString("NullHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null parent.
        /// </summary>
        public static string NullParent {
            get {
                return ResourceManager.GetString("NullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null student.
        /// </summary>
        public static string NullStudent {
            get {
                return ResourceManager.GetString("NullStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent {0}, {1}, age {2}, {3} childs.
        /// </summary>
        public static string ParentParamOut {
            get {
                return ResourceManager.GetString("ParentParamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty Girl {0} {1}, sex: {2}, age: {3}.
        /// </summary>
        public static string PrettyGirlParamOut {
            get {
                return ResourceManager.GetString("PrettyGirlParamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money was written to file {0}.
        /// </summary>
        public static string SavedMoney {
            get {
                return ResourceManager.GetString("SavedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic is too short.
        /// </summary>
        public static string ShortPatronymic {
            get {
                return ResourceManager.GetString("ShortPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Girl {0} {1}, sex: {2}, age: {3}.
        /// </summary>
        public static string SmartGirlParamOut {
            get {
                return ResourceManager.GetString("SmartGirlParamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student {0} {1}, {2}, age {3}.
        /// </summary>
        public static string StudentParamOut {
            get {
                return ResourceManager.GetString("StudentParamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God console here. Create humans or die!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
